testsuites: smp: As build_ltp.sh is changed, so update it accordingly for smp test
git-svn-id: svn://localhost/svn/uclinux-dist/trunk@10376 3e2a5524-39e8-4cb9-84a9-c49da69cba3a

diff --git a/testsuites/smp/testsuites.patch b/testsuites/smp/testsuites.patch
--- a/testsuites/smp/testsuites.patch
+++ b/testsuites/smp/testsuites.patch
@@ -1,9 +1,9 @@
 Index: kernel_test
 ===================================================================
---- kernel_test	(revision 8863)
+--- kernel_test	(revision 10373)
 +++ kernel_test	(working copy)
-@@ -1681,10 +1681,10 @@
- if [ ${AUTO_RUN_STATUS[$(( n + 2 ))]} -eq 1 ] ; then
+@@ -1778,10 +1778,10 @@
+ if [ ${AUTO_RUN_STATUS[$((n+2))]} -eq 1 ] ; then
    echo "Testing LTP..."
  
 -  ltp_args=( [0]="1 1" [1]="1 2" [2]="2 1" [3]="2 2" [4]="1 1 1" )
@@ -17,26 +17,14 @@ Index: kernel_test
    rm -rf $UCLINUX_DIST_PATH/linux-2.6.x
 Index: ltp/build_ltp.sh
 ===================================================================
---- ltp/build_ltp.sh	(revision 8863)
+--- ltp/build_ltp.sh	(revision 10373)
 +++ ltp/build_ltp.sh	(working copy)
-@@ -55,13 +55,13 @@
+@@ -55,7 +55,7 @@
  
- ## We don't need patch for Makefile now ##
- # Patch for Makefiles
--#echo "$0:	Patching Makefiles"
--#patch -p0 < ../Makefile.patch
--#if [ $? -ne 0 ]
--#then
--#	echo "$0:	Error, patching Makefiles failed"
--#	exit 1
--#fi
-+echo "$0:      Patching Makefiles"
-+patch -p0 < ../config.mk.patch
-+if [ $? -ne 0 ]
-+then
-+    echo "$0:       Error, patching Makefiles failed"
-+    exit 1
-+fi
- 
- # Build ltp testsuites
- echo "$0:	Make ..."
+ # configure ltp
+ echo "$0:	Configure ..."
+-./configure --prefix=$CWD/$LTP_SUB_DIR --host=bfin-uclinux --build=i686-pc-linux-gnu CFLAGS="-g -O2 -mstack-check-l1" LDFLAGS="-elf2flt=-s32768" > /dev/null 2>&1
++./configure --prefix=$CWD/$LTP_SUB_DIR --host=bfin-uclinux --build=i686-pc-linux-gnu CFLAGS="-g -O2" LDFLAGS="-elf2flt=-s32768" > /dev/null 2>&1
+ if [ $? -ne 0 ]
+ then
+ 	echo "$0:	Error, configure failed" 
