tools: merge autotools update from blackfin uclinux
Signed-off-by: Thomas Chou <thomas@wytron.com.tw>

diff --git a/tools/cross-pkg-config b/tools/cross-pkg-config
--- a/tools/cross-pkg-config
+++ b/tools/cross-pkg-config
@@ -1,4 +1,8 @@
 #!/bin/sh
+# Copyright 2008 Gentoo Foundation
+# Distributed under the terms of the GNU General Public License v2
+# $Header: $
+
 #
 # This creates a pkg-config frontend that has the form TARGET-pkg-config
 # as this is the utility that autoconf scripts will automatically search
@@ -10,7 +14,7 @@
 #
 # Helper functions.  So very helpful.
 #
-msg_to_stderr() { echo "staging-pkg-config: $*" 1>&2 ; }
+msg_to_stderr() { echo "cross-pkg-config: $*" 1>&2 ; }
 warn() { msg_to_stderr "warning: $*" ; }
 error() {
 	msg_to_stderr "error: $*"
@@ -18,9 +22,29 @@ error() {
 }
 
 #
-# Sanity check: things won't work without the staging directory.
+# Sanity/distro checks
 #
-[ -z "${STAGEDIR}" ] && error "STAGEDIR is not set!"
+if ver=$(pkg-config --version) ; then
+	if [ ${ver#0.1} != ${ver} ] ; then
+		error pkg-config is too old ... upgrade it
+	fi
+else
+	error unable to find pkg-config in PATH
+fi
+
+unset EXTRA_PKG_CONFIG_LIBDIR
+if [ -n "${ROOT}" ] ; then
+	# Gentoo
+	SYSROOT=${ROOT}
+elif [ -n "${STAGEDIR}" ] ; then
+	# uClinux-dist
+	SYSROOT=${STAGEDIR}
+	EXTRA_PKG_CONFIG_LIBDIR=${UCLINUX_PKG_CONFIG_LIBDIR}
+else
+	error "Need \$ROOT or \$STAGEDIR set first"
+fi
+# abort infinite loop due to misconfiguration
+[ "${0##*/}" = "pkg-config" ] && error "aborting infinite loop! (make sure to delete uClinux-dist/tools/pkg-config)"
 
 #
 # Some distributions pollute the pkg-config environment.
@@ -33,9 +57,9 @@ unset PKG_CONFIG_ALLOW_SYSTEM_LIBS
 #
 # Set the pkg-config search paths to our staging directory.
 #
-export PKG_CONFIG_LIBDIR="${STAGEDIR}/usr/lib/pkgconfig"
-if [ -n "${UCLINUX_PKG_CONFIG_LIBDIR}" ] ; then
-	export PKG_CONFIG_LIBDIR="${UCLINUX_PKG_CONFIG_LIBDIR}:${PKG_CONFIG_LIBDIR}"
+export PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig"
+if [ -n "${EXTRA_PKG_CONFIG_LIBDIR}" ] ; then
+	EXTRA_CONFIG_LIBDIR="${EXTRA_PKG_CONFIG_LIBDIR}:${PKG_CONFIG_LIBDIR}"
 fi
 
 #
@@ -50,12 +74,14 @@ case " ${output} " in
 	*" -L/usr/lib64 "*|*" -L/usr/local/lib64 "*|\
 	*" -L /usr/lib64 "*|*" -L /usr/local/lib64 "*)
 		warn "### falling down so here is a dump state ######"
+		export PKG_CONFIG_DEBUG_SPEW="yes"
 		pkg-config --debug "$@" 1>&2
 		warn "### end of dump ###############################"
 		error "host -L paths detected: ${output}"
 		;;
 	*" -I/usr/include"*|*" -I/usr/local/include"*)
 		warn "### falling down so here is a dump state ######"
+		export PKG_CONFIG_DEBUG_SPEW="yes"
 		pkg-config --debug "$@" 1>&2
 		warn "### end of dump ###############################"
 		error "host -I paths detected: ${output}"
